[project]
name = "llm-qna"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.*"
dependencies = [
    "faiss-gpu>=1.7.2",
    "kagglehub>=0.3.11",
    "langchain-community>=0.3.21",
    "langchain-ollama>=0.3.1",
    "typer>=0.15.2",
]
